/*global systemDictionary:true */
"use strict";

systemDictionary = {
    "hekr adapter settings": {
        en: "Adapter settings for hekr",
        de: "Adaptereinstellungen für hekr",
        ru: "Настройки адаптера для hekr",
        pt: "Configurações do adaptador para hekr",
        nl: "Adapterinstellingen voor hekr",
        fr: "Paramètres d'adaptateur pour hekr",
        it: "Impostazioni dell'adattatore per hekr",
        es: "Ajustes del adaptador para hekr",
        pl: "Ustawienia adaptera dla hekr",
        "zh-cn": "hekr的适配器设置",
    },
    "App Email (case sensitive)": {
        en: "App Email (case sensitive)",
        de: "App-E-Mail (Groß-/Kleinschreibung beachten)",
        ru: "Электронная почта приложения (с учетом регистра)",
        pt: "Email do aplicativo (diferencia maiúsculas de minúsculas)",
        nl: "App-e-mail (hoofdlettergevoelig)",
        fr: "E-mail de l'application (sensible à la casse)",
        it: "Email dell'app (maiuscole/minuscole)",
        es: "Correo electrónico de la aplicación (distingue entre mayúsculas y minúsculas)",
        pl: "E-mail aplikacji (wielkość liter ma znaczenie)",
        "zh-cn": "应用电子邮件（区分大小写）",
    },
    "App Password": {
        en: "App Password",
        de: "App-Passwort",
        ru: "Пароль приложения",
        pt: "Senha de app",
        nl: "App-wachtwoord",
        fr: "Mot de passe de l'application",
        it: "Password dell'app",
        es: "Contraseña de la aplicación",
        pl: "Hasło do aplikacji",
        "zh-cn": "应用密码",
    },
    "UDP Remote": {
        en: "Send commands in local network",
        de: "Befehle im lokalen Netzwerk senden",
        ru: "Отправлять команды в локальной сети",
        pt: "Envie comandos na rede local",
        nl: "Opdrachten verzenden in lokaal netwerk",
        fr: "Envoyer des commandes dans le réseau local",
        it: "Invia comandi in rete locale",
        es: "Enviar comandos en la red local",
        pl: "Wysyłaj polecenia w sieci lokalnej",
        "zh-cn": "在本地网络中发送命令",
    },
};
